#ifndef CALL_STATE_H
#define CALL_STATE_H

enum TCallState
{
    CALLSTATE_INVALID = 0,
    CALLSTATE_SEIZURE, 
    CALLSTATE_RECEIVING_DIGITS,
    CALLSTATE_INCOMING,
    CALLSTATE_ACCEPTING,
    CALLSTATE_ANSWERING,
    CALLSTATE_REJECTING,
    CALLSTATE_CONNECTED,
    CALLSTATE_DISCONNECTED,
    CALLSTATE_OUTBOUND_INITIATED,
    CALLSTATE_PLACING,
    CALLSTATE_PROCEEDING,
    CALLSTATE_ALERTING,
    
    CALLSTATE_QTY
};

extern const char *CallStateName[CALLSTATE_QTY];

#endif